P8105 Homework 2
================

## Problem 1

Import data, clean data, handle missing data, select data, mutate data:

``` r
subway_df = 
  read_csv("NYC_Transit_Subway_Entrance_And_Exit_Data.csv", na = c("NA",".","")) |>
  janitor::clean_names() |>
  select(line:entry, vending, ada) |>
  mutate(
    entry = case_match(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE
    )
  )
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### Description of Dataset:

The NYC Transit Subway dataset contains information about subway station
entrances and exits in New York City. The data has been **imported** and
the column names have been **cleaned** to be in a common standard format
(e.g., through underscores for spaces/lowercase consistency). I
**handled missing values** by converting “NA”, “.”, and empty strings to
NA. I **selected** specific columns/variables that are relevant for
further analysis, including the variables **line** (subway line),
**station_name** (name of the station), **station_latitude** and
**station_longitude** (geographic coordinates of the station), **routes
served** (up to 11 routes per station), entrance_type (type of entrance,
e.g., stair, elevator, etc.), **entry** (whether the entrance allows
entry), **vending** (whether there are vending machines at the
entrance), and **ada** (whether the station is ADA compliant). The entry
variable was converted from a character (“YES”/“NO”) to a logical
variable (TRUE for “YES”, FALSE for “NO”). The resulting dataset has
**1868 rows** and **19 columns**. The data is **not tidy**, considering
there are several columns for each route number, for a total of 11
routes/columns for routes served.

### Questions About Data:

There are **465** distinct stations.

``` r
ada_compliant_stations = subway_df |>
  filter(ada == TRUE) |> 
  distinct(line, station_name) |> 
  nrow()

ada_compliant_stations
```

    ## [1] 84

There are **84** stations that are ADA compliant.

``` r
no_vending_entry = subway_df |>
  filter(vending == "NO", entry == TRUE) |>
  nrow()

no_vending_entry
```

    ## [1] 69

There are 69 station entrances/exits without vending that allow
entrance.

``` r
no_vending = subway_df |>
  filter(vending == "NO")|>
  nrow()

no_vending
```

    ## [1] 183

There are 183 station entrances/exits without vending. **69/183 or
37.70%** of station entrances/exits without vending allow entrance.

### Reformatting Data:

``` r
subway_long_df = 
  subway_df |>
  gather(key = route_number, value = route_name, route1:route11) |>
  separate(route_number, into = c("route_str", "route_number"), sep = 5) |>
  select(-route_str)

distinct_a_train_stations = subway_long_df |>
  filter(route_name == "A") |> 
  distinct(line, station_name) |> 
  nrow()

distinct_a_train_stations
```

    ## [1] 60

**60** distinct stations serve the A train.

``` r
ada_compliant_a_train_stations = subway_long_df |>
  filter(route_name == "A", ada == TRUE) |> 
  distinct(line, station_name) |> 
  nrow()

ada_compliant_a_train_stations
```

    ## [1] 17

**17** of the stations that serve the A train are ADA compliant.

## Problem 2

## Problem 3
